---
type: super-spine

# BGP defaults
bgp_default_ipv4_unicast: false
bgp_update_wait_install: false ### Only for virtual lab ###
bgp_update_wait_for_convergence: false
bgp_distance:
  external_routes: 20
  internal_routes: 200
  local_routes: 200
bgp_graceful_restart:
  enabled: true
  restart_time: 300

super_spine:
  defaults:
    platform: 7280CR3-36S
    loopback_ipv4_pool: 192.168.250.0/24

  nodes:
    - name: DCI-1
      id: 1
      bgp_as: 64999
      mgmt_ip: 192.168.0.100/24
# custom evpn bgp
      structured_config:
        router_bgp:
          peer_groups:
          - name: EVPN-OVERLAY-CORE
            type: evpn
            next_hop_unchanged: true
            update_source: Loopback0
            bfd: true
            ebgp_multihop: 15
            send_community: all
            maximum_routes: 0
          neighbors:    
          - ip_address: 192.0.255.17
            remote_as: 65131
            peer_group: EVPN-OVERLAY-CORE
            description: Site1_BGW1_Loopback0      
          - ip_address: 192.0.255.18
            remote_as: 65131
            peer_group: EVPN-OVERLAY-CORE    
            description: Site1_BGW2_Loopback0      
          - ip_address: 192.0.255.19
            remote_as: 65131
            peer_group: EVPN-OVERLAY-CORE   
            description: Site1_BGW3_Loopback0      
          - ip_address: 192.2.255.27
            remote_as: 65231
            peer_group: EVPN-OVERLAY-CORE   
            description: Site2_BGW1_Loopback0      
          - ip_address: 192.2.255.28
            remote_as: 65231
            peer_group: EVPN-OVERLAY-CORE 
            description: Site2_BGW2_Loopback0      
          - ip_address: 192.2.255.29
            remote_as: 65231
            peer_group: EVPN-OVERLAY-CORE   
            description: Site2_BGW3_Loopback0      
          address_family_evpn:
            peer_groups:
              - name: EVPN-OVERLAY-CORE
                activate: true

    - name: DCI-2
      id: 2
      bgp_as: 64999
      mgmt_ip: 192.168.0.101/24
# custom evpn bgp
      structured_config:
        router_bgp:
          peer_groups:
          - name: EVPN-OVERLAY-CORE
            type: evpn
            next_hop_unchanged: true
            update_source: Loopback0
            bfd: true
            ebgp_multihop: 15
            send_community: all
            maximum_routes: 0
          neighbors:    
          - ip_address: 192.0.255.17
            remote_as: 65131
            peer_group: EVPN-OVERLAY-CORE
            description: Site1_BGW1_Loopback0      
          - ip_address: 192.0.255.18
            remote_as: 65131
            peer_group: EVPN-OVERLAY-CORE    
            description: Site1_BGW2_Loopback0      
          - ip_address: 192.0.255.19
            remote_as: 65131
            peer_group: EVPN-OVERLAY-CORE   
            description: Site1_BGW3_Loopback0      
          - ip_address: 192.2.255.27
            remote_as: 65231
            peer_group: EVPN-OVERLAY-CORE   
            description: Site2_BGW1_Loopback0      
          - ip_address: 192.2.255.28
            remote_as: 65231
            peer_group: EVPN-OVERLAY-CORE 
            description: Site2_BGW2_Loopback0      
          - ip_address: 192.2.255.29
            remote_as: 65231
            peer_group: EVPN-OVERLAY-CORE   
            description: Site2_BGW3_Loopback0      
          address_family_evpn:
            peer_groups:
              - name: EVPN-OVERLAY-CORE
                activate: true

    - name: DCI-3
      id: 3
      bgp_as: 64999
      mgmt_ip: 192.168.0.102/24
# custom evpn bgp
      structured_config:
        router_bgp:
          peer_groups:
          - name: EVPN-OVERLAY-CORE
            type: evpn
            next_hop_unchanged: true
            update_source: Loopback0
            bfd: true
            ebgp_multihop: 15
            send_community: all
            maximum_routes: 0
          neighbors:    
          - ip_address: 192.0.255.17
            remote_as: 65131
            peer_group: EVPN-OVERLAY-CORE
            description: Site1_BGW1_Loopback0      
          - ip_address: 192.0.255.18
            remote_as: 65131
            peer_group: EVPN-OVERLAY-CORE    
            description: Site1_BGW2_Loopback0      
          - ip_address: 192.0.255.19
            remote_as: 65131
            peer_group: EVPN-OVERLAY-CORE   
            description: Site1_BGW3_Loopback0      
          - ip_address: 192.2.255.27
            remote_as: 65231
            peer_group: EVPN-OVERLAY-CORE   
            description: Site2_BGW1_Loopback0      
          - ip_address: 192.2.255.28
            remote_as: 65231
            peer_group: EVPN-OVERLAY-CORE 
            description: Site2_BGW2_Loopback0      
          - ip_address: 192.2.255.29
            remote_as: 65231
            peer_group: EVPN-OVERLAY-CORE   
            description: Site2_BGW3_Loopback0      
          address_family_evpn:
            peer_groups:
              - name: EVPN-OVERLAY-CORE
                activate: true

bfd_multihop:
  interval: 1200
  min_rx: 1200
  multiplier: 3